#! /bin/bash

# TODO: Use amixer rather than /proc to determine mute status

# $MUTE is the 'n' of "on" if the sound is muted, the 'f' of "off" if not
MUTE=`pamixer --get-mute`
if [ "$MUTE" == "true" ]; then
      COLOUR="red"
      ICON="ﱝ "
else
      COLOUR="Lightcyan"
      ICON="墳 "
fi

# Returns the current master volume; requires alsa-utils
VALUE=`pamixer --get-volume`

# Format and print
echo "<fc=$COLOUR>$ICON$VALUE%</fc>"
